# Generated by Django 2.1.7 on 2019-05-07 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190505_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 7, 21, 45, 27, 3438)),
        ),
    ]
