# Generated by Django 2.1.7 on 2019-05-13 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190513_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 13, 14, 19, 24, 443960)),
        ),
    ]
